//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwEventManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int EventID { get; set; }
        [Required]
        public string EventName { get; set; }
        [Required]
        public string EventDescription { get; set; }
        [Required]
        public string EventCategory { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public System.DateTime StartDate { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public System.DateTime EndDate { get; set; }
        [Required]
        public Nullable<System.TimeSpan> StartTime { get; set; }
        [Required]
        public Nullable<System.TimeSpan> EndTime { get; set; }
        [Required]
        public string Location { get; set; }
        public bool OpenForRegistration { get; set; }
        [Required]
        public double AdultPrice { get; set; }
        [Required]
        public double ChildPrice { get; set; }
        [Required]
        public string CompanyName { get; set; }
        public string imagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
