//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwEventManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int EventID { get; set; }
        [Required]
        public string PhoneNum { get; set; }
        public string Location { get; set; }
        [Required]
        public int TotalAdult { get; set; }
        [Required]
        public int TotalChild { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<double> totalPrice { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
    }
}
